version: '3'
name: cloakedovpn

services:

  dockovpn:
    image: ahmedahmedeg/dockovpn
    cap_add:
        - NET_ADMIN
    networks:
        - cloaked-ovpn-network
    environment:
        HOST_ADDR: 127.0.0.1
        HOST_TUN_PROTOCOL: tcp
    volumes:
        - ./openvpn_conf:/opt/Dockovpn_data
    restart: always
    
  dockcloak:
    image: ahmedahmedeg/dockcloak
    networks:
        - cloaked-ovpn-network
    ports:
        - 443:443/tcp
    restart: always
    
networks:
  cloaked-ovpn-network: